-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER), H.FLAVOR 
      FROM FIRST_HALF H, JULY J
      WHERE H.FLAVOR = J.FLAVOR
      GROUP BY H.FLAVOR
      ORDER BY SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC)
WHERE ROWNUM <= 3