-- 코드를 입력하세요
SELECT DR_NAME, DR_ID, MCDP_CD, 
TO_CHAR (HIRE_YMD,'YYYY-MM-DD') AS HIRE_YMD
        /*TO_CHAR() 숫자 혹은 날짜 데이터를 원하는 형식의 문자데이터로 형변환*/
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC;