-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN 
      (SELECT CAR_ID 
       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
       WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
       GROUP BY CAR_ID
       HAVING COUNT(CAR_ID) >= 5)
AND TO_NUMBER(TO_CHAR(START_DATE, 'MM')) BETWEEN 8 AND 10
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;